<%-- Document : create_import_receipt --%>
  <%@page contentType="text/html" pageEncoding="UTF-8" %>
    <%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
      <%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
        <c:set var="ctx" value="${pageContext.request.contextPath}" />

        <%-- Internal styles moved to app.css --%>

        <div class="page-wrap">
          <div class="topbar">
            <div class="d-flex align-center gap-12">
              <c:choose>
                <c:when test="${not empty requestId}">
                  <a class="btn" href="${ctx}/home?p=import-request-list">← Back</a>
                </c:when>
                <c:otherwise>
                  <a class="btn" href="${ctx}/home?p=dashboard">← Back</a>
                </c:otherwise>
              </c:choose>
              <h1 class="h1">Create Import Receipt</h1>
            </div>
          </div>

          <div class="card p-24">
            <%-- Source request banner --%>
              <c:if test="${not empty irHeader}">
                <div class="alert alert-info mb-16 font-sm">
                  <b>Source Request:</b>
                  <c:out value="${irHeader.requestCode}" />
                  &nbsp;|&nbsp;
                  <b>Status:</b>
                  <c:out value="${irHeader.status}" />
                  &nbsp;|&nbsp;
                  <b>Expected Import Date:</b>
                  <c:out value="${irHeader.expectedImportDate}" />
                </div>
              </c:if>

              <c:if test="${not empty err}">
                <div class="alert alert-danger mb-16">${fn:escapeXml(err)}</div>
              </c:if>
              <c:if test="${not empty msg}">
                <div class="alert alert-success mb-16">${fn:escapeXml(msg)}</div>
              </c:if>

              <c:set var="isExcel" value="${mode == 'excel'}" />

              <%-- Hide mode tabs when coming from a request --%>
                <c:if test="${empty requestId}">
                  <div class="tab-group mb-20">
                    <button type="button" class="tab-btn ${isExcel ? '' : 'active'}" data-tab="manual">Manual Entry</button>
                    <button type="button" class="tab-btn ${isExcel ? 'active' : ''}" data-tab="excel">Upload Excel With IMEI</button>
                  </div>
                </c:if>

                <!-- ===================== TAB: MANUAL ===================== -->
                <div id="tab-manual" class="ir-tab-panel ${isExcel ? '' : 'active'}">
                  <form id="manualForm" method="post" action="${ctx}/create-import-receipt">
                    <input type="hidden" name="mode" value="manual" />
                    <c:if test="${not empty requestId}">
                      <input type="hidden" name="requestId" value="${requestId}" />
                    </c:if>

                    <div class="h2 mb-10 text-muted">Import Form</div>

                    <div class="form-grid mb-16">
                      <div class="label">Import Code (auto)</div>
                      <div>
                        <input type="text" class="input readonly" name="importCode" value="${fn:escapeXml(importCode)}" readonly />
                        <div class="field-hint">Generated by system</div>
                      </div>

                      <div class="label">Transaction time</div>
                      <div>
                        <input type="datetime-local" class="input" name="receiptDate" value="${fn:escapeXml(receiptDateDefault)}" required />
                      </div>

                      <div class="label">Supplier <span class="text-danger">*</span></div>
                      <div>
                        <select class="select" name="supplierId" required>
                          <option value="" selected disabled>-- Select Supplier --</option>
                          <c:forEach var="s" items="${suppliers}">
                            <option value="${s.id}">${fn:escapeXml(s.name)}</option>
                          </c:forEach>
                        </select>
                      </div>

                      <div class="label">Note</div>
                      <div>
                        <textarea class="textarea" name="note" placeholder="Notes..."></textarea>
                      </div>
                    </div>

                    <div class="h2 mb-10 text-muted">Import Items</div>

                    <div class="table-wrap mb-16">
                      <table class="table" id="itemsTable">
                        <thead>
                          <tr>
                            <th style="width:46px" class="text-center">#</th>
                            <th style="width:160px">Product Name</th>
                            <th style="width:140px">Product Code</th>
                            <th style="width:160px">SKU</th>
                            <th style="width:80px" class="text-center">Qty</th>
                            <th style="width:240px">IMEI Numbers</th>
                            <th style="width:130px">Item Note</th>
                            <th style="width:100px">Created By</th>
                            <th style="width:80px" class="text-center">Action</th>
                          </tr>
                        </thead>
                        <tbody id="itemsTbody"></tbody>
                      </table>
                    </div>

                    <div class="mb-20">
                      <button type="button" class="btn btn-outline" id="btnAddRow">+ Add Product Line</button>
                    </div>

                    <div class="form-actions border-t pt-16 mt-20">
                      <button type="submit" class="btn btn-primary">Save Receipt</button>
                      <c:choose>
                        <c:when test="${not empty requestId}">
                          <a class="btn" href="${ctx}/home?p=import-request-list">Cancel</a>
                        </c:when>
                        <c:otherwise>
                          <a class="btn" href="${ctx}/home?p=import-receipt-list">Cancel</a>
                        </c:otherwise>
                      </c:choose>
                    </div>
                  </form>
                </div>

                <!-- ===================== TAB: EXCEL (hidden in request mode) ===================== -->
                <c:if test="${empty requestId}">
                  <div id="tab-excel" class="ir-tab-panel ${isExcel ? 'active' : ''}">
                    <form method="post" action="${ctx}/create-import-receipt" enctype="multipart/form-data">
                      <input type="hidden" name="mode" value="excel" />

                      <div class="h2 mb-10 text-muted">Import Form (Excel)</div>

                      <div class="alert alert-info mb-16 font-sm">
                        <b>Excel Format:</b> 3 columns: <b>product_code</b>, <b>sku_code</b>, <b>imei</b> (15 digits)
                      </div>

                      <div class="form-grid mb-16">
                        <div class="label">Import Code (auto)</div>
                        <div>
                          <input type="text" class="input readonly" name="importCode" value="${fn:escapeXml(importCode)}" readonly />
                        </div>

                        <div class="label">Excel File (.xlsx)</div>
                        <div>
                          <input type="file" class="input" name="excelFile" accept=".xlsx" required />
                        </div>

                        <div class="label">Transaction time</div>
                        <div>
                          <input type="datetime-local" class="input" name="receiptDate" value="${fn:escapeXml(receiptDateDefault)}" required />
                        </div>

                        <div class="label">Supplier <span class="text-danger">*</span></div>
                        <div>
                          <select class="select" name="supplierId" required>
                            <option value="" selected disabled>-- Select Supplier --</option>
                            <c:forEach var="s" items="${suppliers}">
                              <option value="${s.id}">${fn:escapeXml(s.name)}</option>
                            </c:forEach>
                          </select>
                        </div>

                        <div class="label">Note</div>
                        <div>
                          <textarea class="textarea" name="note" placeholder="Notes..."></textarea>
                        </div>
                      </div>

                      <div class="form-actions border-t pt-16 mt-20">
                        <button type="submit" class="btn btn-primary">Import with Excel</button>
                        <a class="btn" href="${ctx}/home?p=import-receipt-list">Cancel</a>
                      </div>
                    </form>
                  </div>
                </c:if><%-- end c:if empty requestId (excel tab) --%>

          </div>
        </div>

        <script>
          (function () {
            // PRODUCTS: id, code, name
            const PRODUCTS = [
              <c:forEach var="p" items="${products}" varStatus="st">
                { id: "${p.productId}", code: "${fn:escapeXml(p.productCode)}", name: "${fn:escapeXml(p.productName)}" }${!st.last ? ',' : ''}
              </c:forEach>
            ];

            const SKUS = [
              <c:forEach var="k" items="${skus}" varStatus="st">
                { id: "${k.skuId}", code: "${fn:escapeXml(k.skuCode)}", productId: "${k.productId}" }${!st.last ? ',' : ''}
              </c:forEach>
            ];

            // Pre-filled rows from import request (empty array = manual mode)
            const REQUEST_ITEMS = [
              <c:forEach var="it" items="${requestItems}" varStatus="st">
                {
                  productId: "${it.productId}",
                  productCode: "${fn:escapeXml(it.productCode)}",
                  productName: "${fn:escapeXml(it.productName)}",
                  skuId: "${it.skuId}",
                  skuCode: "${fn:escapeXml(it.skuCode)}",
                  qty: ${it.requestQty}
                }${!st.last ? ',' : ''}
              </c:forEach>
            ];

            const IS_REQUEST_MODE = REQUEST_ITEMS.length > 0;

            const CREATED_BY = "${fn:escapeXml(createdByName)}";
            const tbody = document.getElementById("itemsTbody");
            const manualForm = document.getElementById("manualForm");
            let rowCounter = 0;

            // Build Product Name dropdown (or readonly display in request mode)
            function buildProductNameCell(prefill) {
              if (IS_REQUEST_MODE && prefill) {
                // Readonly display
                const inp = document.createElement("input");
                inp.type = "text";
                inp.value = prefill.productName;
                inp.readOnly = true;
                inp.style.background = "var(--surface-2,#f8fafc)";
                inp.style.color = "var(--muted,#64748b)";
                return inp;
              }
              const sel = document.createElement("select");
              sel.required = true;
              sel.style.width = "100%";
              const defOpt = document.createElement("option");
              defOpt.value = "";
              defOpt.textContent = "-- Select Product Name --";
              defOpt.disabled = true;
              defOpt.selected = true;
              sel.appendChild(defOpt);
              PRODUCTS.forEach(p => {
                const opt = document.createElement("option");
                opt.value = p.id;
                opt.textContent = p.name;
                opt.dataset.code = p.code;
                sel.appendChild(opt);
              });
              return sel;
            }

            function buildProductIdInput(prefillId) {
              const inp = document.createElement("input");
              inp.type = "hidden";
              inp.name = "productId";
              if (prefillId) inp.value = prefillId;
              return inp;
            }

            function buildCodeDisplay(prefillCode) {
              const div = document.createElement("div");
              div.className = "mono-text text-sm text-muted";
              div.textContent = prefillCode || "—";
              return div;
            }

            function buildSkuCell(prefill) {
              if (IS_REQUEST_MODE && prefill) {
                // Readonly + hidden skuId
                const wrap = document.createElement("div");
                const hidSku = document.createElement("input");
                hidSku.type = "hidden";
                hidSku.name = "skuId";
                hidSku.value = prefill.skuId;
                const inp = document.createElement("input");
                inp.type = "text";
                inp.value = prefill.skuCode;
                inp.readOnly = true;
                inp.style.background = "var(--surface-2,#f8fafc)";
                inp.style.color = "var(--muted,#64748b)";
                wrap.appendChild(hidSku);
                wrap.appendChild(inp);
                return wrap;
              }
              const sel = document.createElement("select");
              sel.name = "skuId";
              sel.required = true;
              sel.style.width = "100%";
              const defOpt = document.createElement("option");
              defOpt.value = "";
              defOpt.textContent = "-- Select SKU --";
              sel.appendChild(defOpt);
              return sel;
            }

            function refreshSkuOptions(skuSelect, productId) {
              skuSelect.innerHTML = "";
              const defOpt = document.createElement("option");
              defOpt.value = "";
              defOpt.textContent = "-- Select SKU --";
              skuSelect.appendChild(defOpt);
              if (!productId) return;
              SKUS.filter(s => String(s.productId) === String(productId))
                .forEach(s => {
                  const opt = document.createElement("option");
                  opt.value = s.id;
                  opt.textContent = s.code;
                  skuSelect.appendChild(opt);
                });
            }

            function buildImeiBox(rowIdx, qty) {
              const box = document.createElement("div");
              box.className = "ir-imei-box";
              for (let i = 1; i <= qty; i++) {
                const row = document.createElement("div");
                row.className = "ir-imei-row";
                const label = document.createElement("span");
                label.textContent = "IMEI " + i + ":";
                const input = document.createElement("input");
                input.type = "text";
                input.name = "imei_" + rowIdx + "_" + i;
                input.placeholder = "15 digits";
                input.required = true;
                input.maxLength = 15;
                input.className = "input";
                input.addEventListener("input", function () {
                  this.value = this.value.replace(/\D/g, "").slice(0, 15);
                  if (this.value.length === 15) {
                    this.classList.add("valid"); this.classList.remove("invalid");
                  } else if (this.value.length > 0) {
                    this.classList.add("invalid"); this.classList.remove("valid");
                  } else {
                    this.classList.remove("valid", "invalid");
                  }
                });
                row.appendChild(label);
                row.appendChild(input);
                box.appendChild(row);
              }
              return box;
            }

            function addRow(prefill) {
              rowCounter++;
              const rowIdx = rowCounter;
              const tr = document.createElement("tr");
              tr.dataset.rowIdx = rowIdx;

              // #
              const tdNo = document.createElement("td");
              tdNo.className = "center cellNo";
              tdNo.textContent = tbody.children.length + 1;

              // Product Name
              const tdName = document.createElement("td");
              const nameEl = buildProductNameCell(prefill);
              tdName.appendChild(nameEl);

              // Product Code (display + hidden productId)
              const tdCode = document.createElement("td");
              const hidProductId = buildProductIdInput(prefill ? prefill.productId : null);
              const codeDisplay = buildCodeDisplay(prefill ? prefill.productCode : null);
              tdCode.appendChild(hidProductId);
              tdCode.appendChild(codeDisplay);

              // SKU
              const tdSku = document.createElement("td");
              const skuEl = buildSkuCell(prefill);
              tdSku.appendChild(skuEl);

              // Wire up name→code+sku only in manual mode
              if (!IS_REQUEST_MODE) {
                const selName = nameEl; // it's a select in manual mode
                const selSku = skuEl;   // it's a select in manual mode
                selName.addEventListener("change", function () {
                  const pid = this.value;
                  const selectedOpt = this.options[this.selectedIndex];
                  hidProductId.value = pid;
                  codeDisplay.textContent = selectedOpt ? (selectedOpt.dataset.code || "—") : "—";
                  refreshSkuOptions(selSku, pid);
                });
              }

              // Quantity
              const tdQty = document.createElement("td");
              const qtyInp = document.createElement("input");
              qtyInp.type = "number";
              qtyInp.name = "qty";
              qtyInp.min = "1";
              qtyInp.value = prefill ? prefill.qty : "1";
              qtyInp.required = true;
              if (IS_REQUEST_MODE && prefill) {
                // Lock quantity in request mode
                qtyInp.readOnly = true;
                qtyInp.style.background = "var(--surface-2,#f8fafc)";
                qtyInp.style.color = "var(--muted,#64748b)";
              }
              tdQty.appendChild(qtyInp);

              // IMEI
              const tdImei = document.createElement("td");
              tdImei.className = "ir-imei-cell";
              const initQty = prefill ? prefill.qty : 1;
              let imeiBox = buildImeiBox(rowIdx, initQty);
              tdImei.appendChild(imeiBox);

              // Only allow qty change (and IMEI refresh) in manual mode
              if (!IS_REQUEST_MODE) {
                qtyInp.addEventListener("change", function () {
                  let q = parseInt(this.value);
                  if (isNaN(q) || q < 1) { q = 1; this.value = 1; }
                  tdImei.innerHTML = "";
                  imeiBox = buildImeiBox(rowIdx, q);
                  tdImei.appendChild(imeiBox);
                });
              }

              // Item Note
              const tdNote = document.createElement("td");
              const noteInp = document.createElement("input");
              noteInp.type = "text";
              noteInp.name = "itemNote";
              noteInp.placeholder = "Notes";
              tdNote.appendChild(noteInp);

              // Created By
              const tdBy = document.createElement("td");
              tdBy.textContent = CREATED_BY || "Staff";
              tdBy.style.color = "var(--muted,#64748b)";
              tdBy.style.fontSize = "12px";

              // Action — hide delete in request mode
              const tdAct = document.createElement("td");
              tdAct.className = "center";
              if (!IS_REQUEST_MODE) {
                delBtn.type = "button";
                delBtn.className = "btn btn-sm btn-danger";
                delBtn.textContent = "Delete";
                delBtn.addEventListener("click", function () {
                  tr.remove();
                  Array.from(tbody.children).forEach((row, idx) => {
                    const noCell = row.querySelector(".cellNo");
                    if (noCell) noCell.textContent = idx + 1;
                  });
                });
                tdAct.appendChild(delBtn);
              } else {
                tdAct.textContent = "-";
              }

              tr.append(tdNo, tdName, tdCode, tdSku, tdQty, tdImei, tdNote, tdBy, tdAct);
              tbody.appendChild(tr);
            }

            // "+ Add Product Line" button — only visible in manual mode
            const btnAddRow = document.getElementById("btnAddRow");
            if (IS_REQUEST_MODE) {
              btnAddRow.style.display = "none";
            } else {
              btnAddRow.addEventListener("click", () => addRow(null));
            }

            manualForm.addEventListener("submit", function (e) {
              if (tbody.children.length === 0) {
                e.preventDefault();
                alert("Please add at least 1 product line.");
              }
            });

            // Tabs (only in manual mode — tabs are hidden in request mode)
            document.querySelectorAll('.tab-btn').forEach(btn => {
              btn.addEventListener('click', function () {
                const tab = this.dataset.tab;
                document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
                this.classList.add('active');
                document.querySelectorAll('.ir-tab-panel').forEach(p => p.classList.remove('active'));
                document.getElementById('tab-' + tab).classList.add('active');
              });
            });

            // Initialize rows
            if (IS_REQUEST_MODE) {
              REQUEST_ITEMS.forEach(item => addRow(item));
            } else {
              addRow(null);
            }
          })();
        </script>