<%-- 
    Document   : create_import_receipt
    Created on : Feb 6, 2026, 12:36:43 AM
    Author     : Admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<c:set var="ctx" value="${pageContext.request.contextPath}" />

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Create Import Receipt</title>

    <style>
        :root{
            --line:#2e3f95;
            --bg:#f4f4f4;
            --th:#d9d9d9;
        }
        body{font-family: Arial, Helvetica, sans-serif; background:#eee; margin:0;}
        .wrap{padding:14px; background:var(--bg);}
        .frame{border:2px solid var(--line); background:#fff; padding:12px;}
        .h1{font-size:18px; font-weight:700; margin:0 0 10px 0;}
        .sectionTitle{font-weight:700; margin:8px 0 6px;}
        .row{display:flex; gap:10px; margin-bottom:8px; align-items:center;}
        .row label{min-width:140px; font-size:13px;}
        input[type="text"], input[type="datetime-local"], select, textarea{
            width:100%; padding:6px 8px; border:1px solid #333; box-sizing:border-box;
        }
        textarea{height:56px; resize:vertical;}
        .col{flex:1;}
        .tabs{display:flex; gap:6px; margin-bottom:10px;}
        .tabBtn{
            border:1px solid #333; background:#f6f6f6; padding:6px 10px; cursor:pointer;
            font-size:13px;
        }
        .tabBtn.active{background:#fff; font-weight:700;}
        .tabPanel{display:none;}
        .tabPanel.active{display:block;}

        table{border-collapse:collapse; width:100%; table-layout:fixed;}
        th, td{border:1px solid #333; padding:6px; vertical-align:top; font-size:12px;}
        th{background:var(--th); text-align:left;}
        .small{font-size:12px; color:#333;}
        .imeiBox{display:flex; flex-direction:column; gap:4px;}
        .imeiRow{display:flex; gap:6px; align-items:center;}
        .imeiRow span{min-width:48px;}
        .btn{
            border:1px solid #333; background:#f6f6f6; padding:6px 12px; cursor:pointer;
            display:inline-block; text-decoration:none; color:#111; font-size:13px;
        }
        .btn.danger{background:#fff0f0;}
        .btnRow{display:flex; gap:8px; margin-top:10px;}
        .hint{
            background:#c9f2ff; border:1px solid #333; padding:8px; margin:8px 0;
            font-size:12px;
        }
        .err{
            border:1px solid #b00020; background:#ffe9ee; padding:8px; margin-bottom:10px;
            color:#b00020; font-size:13px;
        }
        .ok{
            border:1px solid #0a7f3f; background:#e9fff1; padding:8px; margin-bottom:10px;
            color:#0a7f3f; font-size:13px;
        }
        .w120{width:120px;}
        .w140{width:140px;}
        .w160{width:160px;}
        .w200{width:200px;}
        .center{text-align:center;}
    </style>
</head>
<body>
<div class="wrap">
    <div class="frame">
        <div class="h1">Create Import Receipt</div>

        <c:if test="${not empty err}">
            <div class="err">${fn:escapeXml(err)}</div>
        </c:if>
        <c:if test="${not empty msg}">
            <div class="ok">${fn:escapeXml(msg)}</div>
        </c:if>

        <div class="sectionTitle">Import Form</div>

        <div class="tabs">
            <button type="button" class="tabBtn active" data-tab="manual">Manual Entry</button>
            <button type="button" class="tabBtn" data-tab="excel">Upload Excel With Imei</button>
        </div>

        
        <div id="tab-manual" class="tabPanel active">
            <form method="post" action="${ctx}/create-import-receipt">
                <input type="hidden" name="mode" value="manual"/>

                <div class="row">
                    <label>Import Code (auto)</label>
                    <div class="col">
                        <input type="text" name="importCode" value="${fn:escapeXml(importCode)}" readonly />
                        <div class="small">Generated by system</div>
                    </div>
                   
                </div>

                <div class="row">
                    <label>Transaction time</label>
                    <div class="col">
                        <input type="datetime-local" name="receiptDate" value="${fn:escapeXml(receiptDateDefault)}" required />
                    </div>
                </div>

                <div class="row">
                    <label>Supplier (Optional)</label>
                    <div class="col">
                        <select name="supplierId" id="supplierId">
  <option value="">-- Select Supplier --</option>
  <c:forEach var="s" items="${suppliers}">
  <option value="${s.id}">${fn:escapeXml(s.name)}</option>
</c:forEach>

</select>

                        
                    </div>
                </div>

                <div class="row">
                    <label>Note</label>
                    <div class="col">
                        <textarea name="note" placeholder="Notes..."></textarea>
                    </div>
                </div>

                <div class="sectionTitle">Import Items</div>

                <table id="itemsTable">
                    <thead>
                    <tr>
                        <th class="w120 center">#</th>
                        <th class="w200">Product Code</th>
                        <th class="w200">SKU</th>
                        <th class="w140">Quantity</th>
                        <th>Imei Numbers</th>
                        <th class="w200">Item note</th>
                        <th class="w160">Create By</th>
                        <th class="w120 center">Action</th>
                    </tr>
                    </thead>
                    <tbody id="itemsTbody">
                    <!-- Row template will be added by JS -->
                    </tbody>
                </table>

                <div style="margin-top:8px;">
                    <button type="button" class="btn" id="btnAddRow">+ Add product Line</button>
                </div>

                <div class="btnRow">
                    <button type="submit" class="btn">Save</button>
                    <a class="btn" href="${ctx}/home">Cancel</a>
                </div>
            </form>
        </div>

        
        <div id="tab-excel" class="tabPanel">
            <form method="post" action="${ctx}/create-import-receipt" enctype="multipart/form-data">
                <input type="hidden" name="mode" value="excel"/>

                <div class="hint">
                    <b>Excel Format:</b> Your Excel file must have 3 columns:
                    <b>product_code</b>, <b>sku_code</b>, <b>imei</b> (IMEI must be 15 digits).
                </div>

                <div class="row">
                    <label>Import Code (auto)</label>
                    <div class="col">
                        <input type="text" name="importCode" value="${fn:escapeXml(importCode)}" readonly />
                    </div>
                </div>

                <div class="row">
                    <label>Excel File (.xlsx)</label>
                    <div class="col">
                        <input type="file" name="excelFile" accept=".xlsx" required />
                    </div>
                </div>

                <div class="row">
                    <label>Transaction time</label>
                    <div class="col">
                        <input type="datetime-local" name="receiptDate" value="${fn:escapeXml(receiptDateDefault)}" required />
                    </div>
                </div>

                <div class="row">
                    <label>Supplier (Optional)</label>
                    <div class="col">
                        <select name="supplierId">
                            <option value="">-- Select Supplier --</option>
                           <c:forEach var="s" items="${suppliers}">
  <option value="${s.id}">${fn:escapeXml(s.name)}</option>
</c:forEach>

                        </select>
                        
                    </div>
                </div>

                <div class="row">
                    <label>Note</label>
                    <div class="col">
                        <textarea name="note" placeholder="Notes..."></textarea>
                    </div>
                </div>

                <div class="btnRow">
                    <button type="submit" class="btn">Import with Excel</button>
                    <a class="btn" href="${ctx}/home">Cancel</a>
                </div>
            </form>
        </div>

    </div>
</div>


<script>
    // products: [{productId, productCode}]
      const PRODUCTS = [
    <c:forEach var="p" items="${products}" varStatus="st">
      { productId: ${p.productId}, productCode: "${fn:escapeXml(p.productCode)}" }<c:if test="${!st.last}">,</c:if>
    </c:forEach>
  ];

  // FIX: xóa ký tự "/" lẻ, dùng comment
  const SKUS = [
    <c:forEach var="k" items="${skus}" varStatus="st">
      { skuId: ${k.skuId}, skuCode: "${fn:escapeXml(k.skuCode)}", productId: ${k.productId} }<c:if test="${!st.last}">,</c:if>
    </c:forEach>
  ];

    const CREATED_BY = "${fn:escapeXml(createdByName)}";

    function qs(sel, root=document){ return root.querySelector(sel); }
    function qsa(sel, root=document){ return Array.from(root.querySelectorAll(sel)); }

    
    qsa(".tabBtn").forEach(btn=>{
        btn.addEventListener("click", ()=>{
            qsa(".tabBtn").forEach(b=>b.classList.remove("active"));
            qsa(".tabPanel").forEach(p=>p.classList.remove("active"));
            btn.classList.add("active");
            qs("#tab-" + btn.dataset.tab).classList.add("active");
        });
    });

    // Add row
    const tbody = qs("#itemsTbody");
    qs("#btnAddRow").addEventListener("click", ()=> addRow());

    function buildProductSelect(rowIndex){
        const sel = document.createElement("select");
        sel.name = `productId_${rowIndex}`;
        sel.required = true;

        const opt0 = document.createElement("option");
        opt0.value = "";
        opt0.textContent = "-- Select Product Code --";
        sel.appendChild(opt0);

        PRODUCTS.forEach(p=>{
            const opt = document.createElement("option");
            opt.value = p.productId;
            opt.textContent = p.productCode;
            sel.appendChild(opt);
        });
        return sel;
    }

    function buildSkuSelect(rowIndex){
        const sel = document.createElement("select");
        sel.name = `skuId_${rowIndex}`;
        sel.required = true;

        const opt0 = document.createElement("option");
        opt0.value = "";
        opt0.textContent = "-- Select SKU --";
        sel.appendChild(opt0);
        return sel;
    }

    function refreshSkuOptions(skuSelect, productId){
        skuSelect.innerHTML = "";
        const opt0 = document.createElement("option");
        opt0.value = "";
        opt0.textContent = "-- Select SKU --";
        skuSelect.appendChild(opt0);

        if(!productId) return;

        SKUS.filter(k => String(k.productId) === String(productId))
            .forEach(k=>{
                const opt = document.createElement("option");
                opt.value = k.skuId;
                opt.textContent = k.skuCode;
                skuSelect.appendChild(opt);
            });
    }

    function buildQtyInput(rowIndex){
        const inp = document.createElement("input");
        inp.type = "number";
        inp.min = "1";
        inp.value = "1";
        inp.name = `qty_${rowIndex}`;
        inp.required = true;
        inp.style.width = "100%";
        return inp;
    }

    function buildItemNote(rowIndex){
        const inp = document.createElement("input");
        inp.type = "text";
        inp.name = `itemNote_${rowIndex}`;
        inp.placeholder = "Notes";
        inp.style.width = "100%";
        return inp;
    }

    function buildImeiBox(rowIndex, qty){
        const box = document.createElement("div");
        box.className = "imeiBox";
        for(let i=1;i<=qty;i++){
            const row = document.createElement("div");
            row.className = "imeiRow";

            const label = document.createElement("span");
            label.textContent = "Imei " + i + ":";

            const inp = document.createElement("input");
            inp.type = "text";
            inp.name = `imei_${rowIndex}_${i}`;
            inp.placeholder = "15 digits";
            inp.required = true;
            inp.maxLength = 15;

            inp.addEventListener("input", ()=>{
                inp.value = inp.value.replace(/\D/g, "").slice(0, 15);
            });

            row.appendChild(label);
            row.appendChild(inp);
            box.appendChild(row);
        }
        return box;
    }

    function renumber(){
        qsa("tr", tbody).forEach((tr, idx)=>{
            tr.dataset.idx = (idx+1);
            tr.querySelector(".cellNo").textContent = (idx+1);
        });
        qs("#rowCountHolder")?.remove();
        const holder = document.createElement("input");
        holder.type="hidden";
        holder.id="rowCountHolder";
        holder.name="rowCount";
        holder.value = qsa("tr", tbody).length;
        tbody.parentElement.parentElement.querySelector("form").appendChild(holder);
    }

    function addRow(){
        const rowIndex = qsa("tr", tbody).length + 1;

        const tr = document.createElement("tr");

      
        const tdNo = document.createElement("td");
        tdNo.className="center cellNo";
        tdNo.textContent = rowIndex;

        
        const tdProd = document.createElement("td");
        const selProd = buildProductSelect(rowIndex);
        tdProd.appendChild(selProd);

   
        const tdSku = document.createElement("td");
        const selSku = buildSkuSelect(rowIndex);
        tdSku.appendChild(selSku);

        selProd.addEventListener("change", ()=>{
            refreshSkuOptions(selSku, selProd.value);
        });

     
        const tdQty = document.createElement("td");
        const qtyInp = buildQtyInput(rowIndex);
        tdQty.appendChild(qtyInp);

       
        const tdImei = document.createElement("td");
        let imeiBox = buildImeiBox(rowIndex, parseInt(qtyInp.value || "1", 10));
        tdImei.appendChild(imeiBox);

        qtyInp.addEventListener("change", ()=>{
            let q = parseInt(qtyInp.value || "1", 10);
            if(isNaN(q) || q < 1) q = 1;
            qtyInp.value = q;

            tdImei.innerHTML = "";
            imeiBox = buildImeiBox(rowIndex, q);
            tdImei.appendChild(imeiBox);
        });

      
        const tdNote = document.createElement("td");
        tdNote.appendChild(buildItemNote(rowIndex));

       
        const tdBy = document.createElement("td");
        tdBy.textContent = CREATED_BY || "Staff";

        
        const tdAct = document.createElement("td");
        tdAct.className="center";
        const delBtn = document.createElement("button");
        delBtn.type="button";
        delBtn.className="btn danger";
        delBtn.textContent="Delete";
        delBtn.addEventListener("click", ()=>{
            tr.remove();
            renumber();
        });
        tdAct.appendChild(delBtn);

        tr.appendChild(tdNo);
        tr.appendChild(tdProd);
        tr.appendChild(tdSku);
        tr.appendChild(tdQty);
        tr.appendChild(tdImei);
        tr.appendChild(tdNote);
        tr.appendChild(tdBy);
        tr.appendChild(tdAct);

        tbody.appendChild(tr);
        renumber();
    }

    
    addRow();

    
    qs("#btnRegenCode").addEventListener("click", ()=>{
        window.location = "${ctx}/warehouse/create-import-receipt?regen=1";
    });
</script>
</body>
</html>
