<%-- 
    Document   : create_export_receipt
    Created on : Feb 12, 2026, 12:47:26 PM
    Author     : Admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<c:set var="ctx" value="${pageContext.request.contextPath}" />

<div class="page-wrap-md">
    <div class="card">
        <div class="card-body">

            <div class="topbar" style="margin-bottom:18px;">
                <div style="display:flex; align-items:center; gap:10px;">
                    <a class="btn btn-outline" href="${ctx}/home?p=dashboard">← Back</a>
                    <div class="title">Create Export Receipt</div>
                </div>
            </div>

            <c:if test="${not empty err}">
                <div class="msg-err"><c:out value="${err}"/></div>
            </c:if>
            <c:if test="${not empty msg}">
                <div class="msg-ok"><c:out value="${msg}"/></div>
            </c:if>

            <h2 class="h2" style="margin:0 0 14px;">Export Form</h2>

            <c:if test="${not empty erHeader}">
                <div class="card" style="background:var(--primary-light); border-color:var(--primary-border); margin-bottom:16px;">
                    <div class="card-body" style="padding:12px 16px; font-size:13px;">
                        <b>Source Request:</b> ${fn:escapeXml(erHeader.requestCode)}
                        &nbsp; | &nbsp;
                        <b>Status:</b> ${fn:escapeXml(erHeader.status)}
                        &nbsp; | &nbsp;
                        <b>Expected Export Date:</b> <c:out value="${erHeader.expectedExportDate}"/>
                    </div>
                </div>
            </c:if>

            <div class="tab-group" style="margin-bottom:18px;">
                <button type="button" class="tab-btn active" data-tab="manual">Manual Entry</button>
                <c:if test="${empty sourceRequestId}">
                    <button type="button" class="tab-btn" data-tab="excel">Upload Excel With IMEI</button>
                </c:if>
            </div>

            <!-- ================= Manual ================= -->
            <div id="tab-manual" class="tabPanel active">
                <form id="manualForm" method="post" action="${ctx}/create-export-receipt">
                    <input type="hidden" name="mode" value="manual"/>
                    <c:if test="${not empty sourceRequestId}">
                        <input type="hidden" name="requestId" value="${sourceRequestId}"/>
                    </c:if>

                    <div class="form-grid">
                        <div class="label">Export Code (auto)</div>
                        <div>
                            <input class="input readonly" type="text" name="exportCode"
                                   value="${fn:escapeXml(exportCode)}" readonly />
                            <div class="field-hint">Generated by system</div>
                        </div>

                        <div class="label">Transaction time</div>
                        <div>
                            <input class="input" type="datetime-local" name="receiptDate"
                                   value="${fn:escapeXml(receiptDateDefault)}" required />
                        </div>

                        <div class="label">Created by (Sale)</div>
                        <div>
                            <input class="input readonly" type="text"
                                   value="${fn:escapeXml(createdByName)}" readonly />
                        </div>

                        <div class="label">Note</div>
                        <div>
                            <textarea class="textarea" name="note"
                                      placeholder="Optional note for warehouse staff..."></textarea>
                        </div>
                    </div>

                    <h2 class="h2" style="margin:22px 0 12px;">Export Items</h2>

                    <div style="overflow-x:auto;">
                        <table id="itemsTable" class="table">
                            <thead>
                                <tr>
                                    <th class="center" style="width:60px;">#</th>
                                    <th style="width:220px;">Product Name</th>
                                    <th style="width:180px;">Product Code</th>
                                    <th style="width:200px;">SKU</th>
                                    <th style="width:120px;" class="text-center">Qty</th>
                                    <th style="width:280px;">IMEI Numbers</th>
                                    <th style="width:180px;">Item Note</th>
                                    <th class="center" style="width:120px;">Action</th>
                                </tr>
                            </thead>
                            <tbody id="itemsTbody"></tbody>
                        </table>
                    </div>

                    <c:if test="${empty sourceRequestId}">
                        <div style="margin-top:10px;">
                            <button type="button" class="btn btn-outline" id="btnAddRow">+ Add Product Line</button>
                        </div>
                    </c:if>

                    <div class="form-actions" style="justify-content:flex-start; margin-top:16px;">
                        <button type="submit" class="btn btn-primary">Create Receipt</button>
                        <a class="btn" href="${ctx}/home?p=export-receipt-list">Cancel</a>
                    </div>
                </form>
            </div>

            <!-- ================= Excel ================= -->
            <c:if test="${empty sourceRequestId}">
                <div id="tab-excel" class="tabPanel" style="display:none;">
                    <form method="post" action="${ctx}/create-export-receipt" enctype="multipart/form-data">
                        <input type="hidden" name="mode" value="excel"/>

                        <div class="card" style="background:var(--primary-light); border-color:var(--primary-border); margin-bottom:16px;">
                            <div class="card-body" style="padding:12px 16px; font-size:13px;">
                                <b>Excel Format:</b> 4 columns:
                                <b>product_code</b>, <b>sku_code</b>, <b>imei</b> (15 digits), <b>item_note</b> (optional)
                            </div>
                        </div>

                        <div class="form-grid">
                            <div class="label">Export Code (auto)</div>
                            <div>
                                <input class="input readonly" type="text" name="exportCode"
                                       value="${fn:escapeXml(exportCode)}" readonly />
                            </div>

                            <div class="label">Excel File (.xlsx)</div>
                            <div>
                                <input class="input" type="file" name="excelFile" accept=".xlsx" required />
                            </div>

                            <div class="label">Transaction time</div>
                            <div>
                                <input class="input" type="datetime-local" name="receiptDate"
                                       value="${fn:escapeXml(receiptDateDefault)}" required />
                            </div>

                            <div class="label">Created by (Sale)</div>
                            <div>
                                <input class="input readonly" type="text"
                                       value="${fn:escapeXml(createdByName)}" readonly />
                            </div>

                            <div class="label">Note</div>
                            <div>
                                <textarea class="textarea" name="note"
                                          placeholder="Optional note for warehouse staff..."></textarea>
                            </div>
                        </div>

                        <div class="form-actions" style="justify-content:flex-start; margin-top:16px;">
                            <button type="submit" class="btn btn-primary">Create with Excel</button>
                            <a class="btn" href="${ctx}/home?p=export-receipt-list">Cancel</a>
                        </div>
                    </form>
                </div>
            </c:if>

        </div>
    </div>
</div>

<script>
    (function () {
    const PRODUCTS = [
    <c:forEach var="p" items="${products}" varStatus="st">
    {
    id: ${p.productId},
            code: "${fn:escapeXml(p.productCode)}",
            name: "${fn:escapeXml(p.productName)}"
    }<c:if test="${!st.last}">,</c:if>
    </c:forEach>
    ];
    const SKUS = [
    <c:forEach var="k" items="${skus}" varStatus="st">
    {
    id: ${k.skuId},
            code: "${fn:escapeXml(k.skuCode)}",
            productId: ${k.productId}
    }<c:if test="${!st.last}">,</c:if>
    </c:forEach>
    ];
    const REQUEST_ITEMS = [
    <c:forEach var="it" items="${erItems}" varStatus="st">
    {
    productId: ${it.productId},
            productName: "${fn:escapeXml(it.productName)}",
            productCode: "${fn:escapeXml(it.productCode)}",
            skuId: ${it.skuId},
            skuCode: "${fn:escapeXml(it.skuCode)}",
            qty: ${it.requestQty}
    }<c:if test="${!st.last}">,</c:if>
    </c:forEach>
    ];
    const IS_FROM_REQUEST = ${not empty sourceRequestId};
    const tbody = document.getElementById("itemsTbody");
    const manualForm = document.getElementById("manualForm");
    const btnAddRow = document.getElementById("btnAddRow");
    let rowCounter = 0;
    async function fetchImeisBySku(skuId) {
    try {
    const res = await fetch("${ctx}/api/available-imeis?skuId=" + encodeURIComponent(skuId));
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data) ? data : [];
    } catch (e) {
    return [];
    }
    }

    async function loadImeisForLockedOrPrefillRow(skuId, rowIdx, qtyInp, tdImei) {
    const currentImeiOptions = skuId ? await fetchImeisBySku(skuId) : [];
    tdImei.innerHTML = "";
    const imeiBox = buildImeiBox(rowIdx, parseInt(qtyInp.value) || 1, currentImeiOptions);
    tdImei.appendChild(imeiBox);
    syncImeiDisabledOptions();
    if (skuId && currentImeiOptions.length === 0) {
    alert("No available IMEIs in stock for this SKU.");
    }
    }

    function buildProductNameSelect() {
    const sel = document.createElement("select");
    sel.required = true;
    sel.className = "select";
    sel.innerHTML = '<option value="">-- Select Product Name --</option>';
    PRODUCTS.forEach(p => {
    const opt = document.createElement("option");
    opt.value = p.id;
    opt.textContent = p.name;
    opt.dataset.code = p.code;
    sel.appendChild(opt);
    });
    return sel;
    }

    function buildProductCodeDisplay(initialCode) {
    const div = document.createElement("div");
    div.style.padding = "10px 14px";
    div.style.border = "1px solid var(--border)";
    div.style.borderRadius = "10px";
    div.style.minHeight = "42px";
    div.style.display = "flex";
    div.style.alignItems = "center";
    div.style.background = "var(--surface-2)";
    div.style.color = "var(--muted)";
    div.style.fontSize = "14px";
    div.style.fontWeight = "600";
    div.textContent = initialCode || "—";
    return div;
    }

    function buildSkuSelect() {
    const sel = document.createElement("select");
    sel.required = true;
    sel.className = "select";
    sel.innerHTML = '<option value="">-- Select SKU --</option>';
    return sel;
    }

    function refreshSkuOptions(skuSelect, productId) {
    skuSelect.innerHTML = '<option value="">-- Select SKU --</option>';
    if (!productId) return;
    SKUS.filter(s => String(s.productId) === String(productId)).forEach(s => {
    const opt = document.createElement("option");
    opt.value = s.id;
    opt.textContent = s.code;
    skuSelect.appendChild(opt);
    });
    }

    function buildImeiBox(rowIdx, qty, imeiOptions) {
    const box = document.createElement("div");
    box.style.display = "flex";
    box.style.flexDirection = "column";
    box.style.gap = "6px";
    box.style.minWidth = "220px";
    for (let i = 1; i <= qty; i++) {
    const row = document.createElement("div");
    row.style.display = "flex";
    row.style.gap = "6px";
    row.style.alignItems = "center";
    const label = document.createElement("span");
    label.textContent = "IMEI " + i + ":";
    label.style.minWidth = "56px";
    label.style.fontSize = "12px";
    label.style.color = "var(--muted)";
    label.style.fontWeight = "600";
    const sel = document.createElement("select");
    sel.className = "select";
    sel.name = "imei_" + rowIdx + "_" + i;
    sel.required = true;
    sel.innerHTML = '<option value="">-- Select IMEI --</option>';
    sel.addEventListener("change", syncImeiDisabledOptions);
    (imeiOptions || []).forEach(v => {
    const opt = document.createElement("option");
    opt.value = v;
    opt.textContent = v;
    sel.appendChild(opt);
    });
    row.appendChild(label);
    row.appendChild(sel);
    box.appendChild(row);
    }

    return box;
    }

    function renumber() {
    Array.from(tbody.children).forEach((row, idx) => {
    const noCell = row.querySelector(".cellNo");
    if (noCell) noCell.textContent = idx + 1;
    });
    }

    function addRow(prefill) {
    rowCounter++;
    const rowIdx = rowCounter;
    const isLocked = !!prefill && IS_FROM_REQUEST;
    const tr = document.createElement("tr");
    tr.dataset.rowIdx = rowIdx;
    const hiddenRowKey = document.createElement("input");
    hiddenRowKey.type = "hidden";
    hiddenRowKey.name = "rowKey";
    hiddenRowKey.value = String(rowIdx);
    tr.appendChild(hiddenRowKey);
    const tdNo = document.createElement("td");
    tdNo.className = "center cellNo";
    tdNo.textContent = tbody.children.length + 1;
    const tdProdName = document.createElement("td");
    const selProd = buildProductNameSelect();
    selProd.name = "productId_" + rowIdx;
    const tdProdCode = document.createElement("td");
    const productCodeBox = buildProductCodeDisplay("");
    const tdSku = document.createElement("td");
    const selSku = buildSkuSelect();
    selSku.name = "skuId_" + rowIdx;
    selSku.disabled = true;
    const tdQty = document.createElement("td");
    tdQty.className = "text-center";
    const qtyInp = document.createElement("input");
    qtyInp.type = "number";
    qtyInp.min = "1";
    qtyInp.value = prefill ? prefill.qty : "1";
    qtyInp.required = true;
    qtyInp.name = "qty_" + rowIdx;
    qtyInp.className = "form-control form-control-sm text-center";
    qtyInp.style.minWidth = "80px";
    qtyInp.style.maxWidth = "90px";
    qtyInp.style.margin = "0 auto";
    const tdImei = document.createElement("td");
    let currentImeiOptions = [];
    let imeiBox = buildImeiBox(rowIdx, 1, currentImeiOptions);
    tdImei.appendChild(imeiBox);
    const tdNote = document.createElement("td");
    const noteInp = document.createElement("input");
    noteInp.type = "text";
    noteInp.name = "itemNote_" + rowIdx;
    noteInp.placeholder = "Notes";
    noteInp.className = "input";
    tdNote.appendChild(noteInp);
    const tdAct = document.createElement("td");
    tdAct.className = "center";
    const delBtn = document.createElement("button");
    delBtn.type = "button";
    delBtn.className = "btn btn-danger btn-sm";
    delBtn.textContent = "Delete";
    delBtn.addEventListener("click", function () {
    tr.remove();
    renumber();
    syncImeiDisabledOptions();
    });
    if (prefill) {
    let matchedProduct = null;
    if (prefill.productId) {
    matchedProduct = PRODUCTS.find(p => String(p.id) === String(prefill.productId));
    }
    if (!matchedProduct && prefill.productCode) {
    matchedProduct = PRODUCTS.find(p => p.code === prefill.productCode);
    }

    if (matchedProduct) {
    selProd.value = String(matchedProduct.id);
    productCodeBox.textContent = matchedProduct.code || "—";
    refreshSkuOptions(selSku, matchedProduct.id);
    selSku.disabled = false;
    let matchedSku = null;
    if (prefill.skuId) {
    matchedSku = SKUS.find(s => String(s.id) === String(prefill.skuId));
    }
    if (!matchedSku && prefill.skuCode) {
    matchedSku = SKUS.find(s =>
            String(s.productId) === String(matchedProduct.id) &&
            s.code === prefill.skuCode
            );
    }

    if (matchedSku) {
    selSku.value = String(matchedSku.id);
    }
    }

    qtyInp.value = prefill.qty || 1;
    if (prefill.itemNote) {
    noteInp.value = prefill.itemNote;
    }
    }

    if (isLocked) {
    const hiddenProd = document.createElement("input");
    hiddenProd.type = "hidden";
    hiddenProd.name = "productId_" + rowIdx;
    hiddenProd.value = selProd.value;
    const hiddenSku = document.createElement("input");
    hiddenSku.type = "hidden";
    hiddenSku.name = "skuId_" + rowIdx;
    hiddenSku.value = selSku.value;
    const hiddenQty = document.createElement("input");
    hiddenQty.type = "hidden";
    hiddenQty.name = "qty_" + rowIdx;
    hiddenQty.value = qtyInp.value;
    selProd.disabled = true;
    selSku.disabled = true;
    qtyInp.readOnly = true;
    qtyInp.className = "form-control form-control-sm text-center";
    qtyInp.style.minWidth = "80px";
    qtyInp.style.maxWidth = "90px";
    qtyInp.style.margin = "0 auto";
    qtyInp.style.background = "#f8f9fa";
    noteInp.readOnly = false;
    tdProdName.appendChild(selProd);
    tdProdName.appendChild(hiddenProd);
    tdProdCode.appendChild(productCodeBox);
    tdSku.appendChild(selSku);
    tdSku.appendChild(hiddenSku);
    tdQty.appendChild(qtyInp);
    tdQty.appendChild(hiddenQty);
    tdAct.textContent = "-";
    } else {
    tdProdName.appendChild(selProd);
    tdProdCode.appendChild(productCodeBox);
    tdSku.appendChild(selSku);
    tdQty.appendChild(qtyInp);
    tdAct.appendChild(delBtn);
    selProd.addEventListener("change", function () {
    const selectedOpt = this.options[this.selectedIndex];
    const productId = this.value;
    productCodeBox.textContent = selectedOpt && selectedOpt.dataset.code
            ? selectedOpt.dataset.code
            : "—";
    refreshSkuOptions(selSku, productId);
    selSku.disabled = !productId;
    selSku.value = "";
    currentImeiOptions = [];
    tdImei.innerHTML = "";
    imeiBox = buildImeiBox(rowIdx, parseInt(qtyInp.value) || 1, currentImeiOptions);
    tdImei.appendChild(imeiBox);
    syncImeiDisabledOptions();
    });
    selSku.addEventListener("change", async function () {
    const skuId = this.value;
    currentImeiOptions = skuId ? await fetchImeisBySku(skuId) : [];
    tdImei.innerHTML = "";
    imeiBox = buildImeiBox(rowIdx, parseInt(qtyInp.value) || 1, currentImeiOptions);
    tdImei.appendChild(imeiBox);
    syncImeiDisabledOptions();
    if (skuId && currentImeiOptions.length === 0) {
    alert("No available IMEIs in stock for this SKU.");
    }
    });
    qtyInp.addEventListener("input", function () {
    let q = parseInt(this.value) || 1;
    if (q < 1) q = 1;
    this.value = q;
    tdImei.innerHTML = "";
    imeiBox = buildImeiBox(rowIdx, q, currentImeiOptions);
    tdImei.appendChild(imeiBox);
    syncImeiDisabledOptions();
    });
    }

    if (prefill && selSku.value) {
    loadImeisForLockedOrPrefillRow(selSku.value, rowIdx, qtyInp, tdImei);
    } else {
    syncImeiDisabledOptions();
    }

    tr.appendChild(tdNo);
    tr.appendChild(tdProdName);
    tr.appendChild(tdProdCode);
    tr.appendChild(tdSku);
    tr.appendChild(tdQty);
    tr.appendChild(tdImei);
    tr.appendChild(tdNote);
    tr.appendChild(tdAct);
    tbody.appendChild(tr);
    }

    function getSelectedImeisBySku() {
    const map = new Map();
    Array.from(tbody.children).forEach(tr => {
    const rowIdx = tr.dataset.rowIdx;
    const skuSel = tr.querySelector(`select[name="skuId_${rowIdx}"]`);
    const hiddenSku = tr.querySelector(`input[type="hidden"][name="skuId_${rowIdx}"]`);
    const skuId = hiddenSku ? hiddenSku.value : (skuSel ? skuSel.value : "");
    if (!skuId) return;
    const selects = tr.querySelectorAll(`select[name^="imei_${rowIdx}_"]`);
    selects.forEach(s => {
    const v = (s.value || "").trim();
    if (!v) return;
    if (!map.has(skuId)) {
    map.set(skuId, new Set());
    }
    map.get(skuId).add(v);
    });
    });
    return map;
    }

    function syncImeiDisabledOptions() {
    const selectedMap = getSelectedImeisBySku();
    function countSelectedInSku(skuId, imeiVal) {
    let count = 0;
    Array.from(tbody.children).forEach(tr2 => {
    const rowIdx2 = tr2.dataset.rowIdx;
    const skuSel2 = tr2.querySelector(`select[name="skuId_${rowIdx2}"]`);
    const hiddenSku2 = tr2.querySelector(`input[type="hidden"][name="skuId_${rowIdx2}"]`);
    const skuId2 = hiddenSku2 ? hiddenSku2.value : (skuSel2 ? skuSel2.value : "");
    if (skuId2 !== skuId) return;
    const s2 = tr2.querySelectorAll(`select[name^="imei_${rowIdx2}_"]`);
    s2.forEach(x => {
    if ((x.value || "").trim() === imeiVal) {
    count++;
    }
    });
    });
    return count;
    }

    Array.from(tbody.children).forEach(tr => {
    const rowIdx = tr.dataset.rowIdx;
    const skuSel = tr.querySelector(`select[name="skuId_${rowIdx}"]`);
    const hiddenSku = tr.querySelector(`input[type="hidden"][name="skuId_${rowIdx}"]`);
    const skuId = hiddenSku ? hiddenSku.value : (skuSel ? skuSel.value : "");
    if (!skuId) return;
    const chosen = selectedMap.get(skuId) || new Set();
    const selects = tr.querySelectorAll(`select[name^="imei_${rowIdx}_"]`);
    selects.forEach(sel => {
    const myVal = (sel.value || "").trim();
    Array.from(sel.options).forEach(opt => {
    if (!opt.value) return;
    opt.hidden = (chosen.has(opt.value) && opt.value !== myVal);
    opt.disabled = false;
    });
    if (myVal && countSelectedInSku(skuId, myVal) > 1) {
    sel.value = "";
    }

    const newVal = (sel.value || "").trim();
    Array.from(sel.options).forEach(opt => {
    if (!opt.value) return;
    opt.hidden = (chosen.has(opt.value) && opt.value !== newVal);
    });
    });
    });
    }

    if (btnAddRow) {
    btnAddRow.addEventListener("click", function () {
    addRow();
    });
    }

    manualForm.addEventListener("submit", function (e) {
    const rows = tbody.children;
    if (rows.length === 0) {
    e.preventDefault();
    alert("Please add at least 1 product line.");
    return;
    }

    const fd = new FormData(manualForm);
    for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const rowIdx = row.dataset.rowIdx;
    const productId = (fd.get("productId_" + rowIdx) || "").toString().trim();
    const skuId = (fd.get("skuId_" + rowIdx) || "").toString().trim();
    const qty = parseInt((fd.get("qty_" + rowIdx) || "0").toString(), 10) || 0;
    if (!productId || !skuId || qty < 1) {
    e.preventDefault();
    alert("Row " + (i + 1) + ": Please fill Product Name, SKU and Quantity");
    return;
    }

    const imeiSet = new Set();
    for (let j = 1; j <= qty; j++) {
    const sel = row.querySelector('select[name="imei_' + rowIdx + '_' + j + '"]');
    const v = sel ? (sel.value || "").trim() : "";
    if (!v) {
    e.preventDefault();
    alert("Row " + (i + 1) + ", IMEI " + j + ": Please select an IMEI");
    return;
    }

    if (imeiSet.has(v)) {
    e.preventDefault();
    alert("Row " + (i + 1) + ": Duplicate IMEI selected: " + v);
    return;
    }

    imeiSet.add(v);
    }
    }
    });
    document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', function () {
    const tab = this.dataset.tab;
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    this.classList.add('active');
    document.querySelectorAll('.tabPanel').forEach(p => {
    p.classList.remove('active');
    p.style.display = 'none';
    });
    const target = document.getElementById('tab-' + tab);
    if (target) {
    target.classList.add('active');
    target.style.display = 'block';
    }
    });
    });
    if (REQUEST_ITEMS.length > 0) {
    REQUEST_ITEMS.forEach(item => addRow(item));
    } else {
    addRow();
    }
    })();
</script>
