/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package controller;

/**
 *
 * @author Admin
 */


import dal.DBContext;
import dal.ImportReceiptDAO;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;

import model.ImportReceiptDetail;
import model.ImportReceiptLineDetail;

import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.openpdf.text.*;
import org.openpdf.text.pdf.*;
import org.openpdf.text.pdf.draw.LineSeparator;

@WebServlet(name = "ImportReceiptPdf", urlPatterns = {"/import-receipt-pdf"})
public class ImportReceiptPdf extends HttpServlet {

    // ===== fonts =====
    private static final Font H1 = new Font(Font.HELVETICA, 20, Font.BOLD);
    private static final Font H2 = new Font(Font.HELVETICA, 14, Font.BOLD);
    private static final Font B  = new Font(Font.HELVETICA, 11, Font.BOLD);
    private static final Font N  = new Font(Font.HELVETICA, 11, Font.NORMAL);
    private static final Font SMALL = new Font(Font.HELVETICA, 9, Font.NORMAL);

    // ===== Footer Event: vẽ footer cố định ở đáy mọi trang =====
    private static class FooterEvent extends PdfPageEventHelper {

        private final String generatedAt =
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            String text = "Footer: Generated by Mobile WMS - " + generatedAt;

            // canh giữa theo vùng content (left..right)
            float x = (document.left() + document.right()) / 2f;

            // đáy trang: nằm trong bottom margin (luôn ở dưới cùng)
            // chỉnh số này để sát đáy hơn / cao lên:
            float y = document.bottom() - 12;

            ColumnText.showTextAligned(
                    cb,
                    Element.ALIGN_CENTER,
                    new Phrase(text, SMALL),
                    x,
                    y,
                    0
            );
        }
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        String idRaw = req.getParameter("id");
        if (idRaw == null || idRaw.isBlank()) {
            resp.sendError(400, "Missing id");
            return;
        }

        long importId;
        try {
            importId = Long.parseLong(idRaw.trim());
        } catch (Exception e) {
            resp.sendError(400, "Invalid id");
            return;
        }

        ImportReceiptDAO dao = new ImportReceiptDAO();
        ImportReceiptDetail header;
        List<ImportReceiptLineDetail> lines;

        try (var con = DBContext.getConnection()) {
            header = dao.getDetailHeader(con, importId);
            if (header == null) {
                resp.sendError(404, "Import receipt not found");
                return;
            }
            lines = dao.getDetailLines(con, importId);
        } catch (Exception e) {
            throw new ServletException(e);
        }

        String fileName = "import-receipt-" + safe(header.getImportCode()) + ".pdf";
        String encoded = URLEncoder.encode(fileName, StandardCharsets.UTF_8).replace("+", "%20");

        resp.setContentType("application/pdf");
        resp.setHeader("Content-Disposition", "attachment; filename*=UTF-8''" + encoded);

        // ✅ tăng bottom margin để chừa chỗ footer (quan trọng!)
        Document doc = new Document(PageSize.A4, 48, 48, 42, 70);

        try {
            PdfWriter writer = PdfWriter.getInstance(doc, resp.getOutputStream());

            // ✅ gắn footer event => footer luôn dưới cùng mọi trang
            writer.setPageEvent(new FooterEvent());

            doc.open();

            addHeader(doc, header);
            addItemsTable(doc, lines);
            addSummary(doc, lines);
            addSignatures(doc);

            // ❌ KHÔNG doc.add(addFooter) nữa

        } catch (Exception e) {
            throw new ServletException(e);
        } finally {
            if (doc.isOpen()) doc.close();
        }
    }

    private void addHeader(Document doc, ImportReceiptDetail h) throws DocumentException {

        PdfPTable top = new PdfPTable(new float[]{70, 30});
        top.setWidthPercentage(100);

        PdfPCell left = cellNoBorder(new Phrase("Mobile Warehouse Management", H1));
        left.setPaddingBottom(6);
        top.addCell(left);

        PdfPCell right = cellNoBorder(new Phrase(
                "Receipt No: " + safe(h.getImportCode()) + "\n" +
                "Date: " + safe(fmt(h.getReceiptDate())),
                B
        ));
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);
        right.setNoWrap(true);
        top.addCell(right);

        PdfPCell sub = cellNoBorder(new Phrase("[Address | Phone | Email]", SMALL));
        sub.setColspan(2);
        sub.setPaddingBottom(10);
        top.addCell(sub);

        doc.add(top);

        Paragraph title = new Paragraph("IMPORT RECEIPT", new Font(Font.HELVETICA, 16, Font.BOLD));
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingBefore(6);
        title.setSpacingAfter(6);
        doc.add(title);

        doc.add(lineSeparator());

        PdfPTable info = new PdfPTable(new float[]{55, 45});
        info.setWidthPercentage(100);

        info.addCell(cellNoBorder(new Phrase("Supplier: " + safe(h.getSupplierName()), N)));
        info.addCell(cellNoBorder(new Phrase("Created by: " + safe(h.getCreatedByName()), N)));

        info.addCell(cellNoBorder(new Phrase("Status: " + safe(h.getStatus()), N)));
        info.addCell(cellNoBorder(new Phrase("", N)));

        PdfPCell noteLabel = cellNoBorder(new Phrase("Note:", N));
        noteLabel.setColspan(2);
        noteLabel.setPaddingTop(6);
        info.addCell(noteLabel);

        PdfPCell noteVal = cellNoBorder(new Phrase(safe(h.getNote()), N));
        noteVal.setColspan(2);
        noteVal.setPaddingLeft(28);
        noteVal.setPaddingBottom(6);
        info.addCell(noteVal);

        doc.add(info);
        doc.add(lineSeparator());
    }

    private void addItemsTable(Document doc, List<ImportReceiptLineDetail> lines) throws DocumentException {

        Paragraph items = new Paragraph("ITEMS", H2);
        items.setSpacingBefore(6);
        items.setSpacingAfter(8);
        doc.add(items);

        PdfPTable t = new PdfPTable(new float[]{6, 20, 26, 10, 10, 28});
        t.setWidthPercentage(100);

        t.addCell(th("#"));
        t.addCell(th("Product"));
        t.addCell(th("SKU (optional)"));
        t.addCell(th("In Stock"));
        t.addCell(th("Quantity"));
        t.addCell(th("IMEI List (optional)"));

        int idx = 1;
        if (lines != null) {
            for (ImportReceiptLineDetail it : lines) {
                t.addCell(td(String.valueOf(idx++), Element.ALIGN_LEFT));
                t.addCell(td(safe(it.getProductCode()), Element.ALIGN_LEFT));
                t.addCell(td(safe(it.getSkuCode()), Element.ALIGN_LEFT));
                t.addCell(td(String.valueOf(it.getInStock()), Element.ALIGN_LEFT));
                t.addCell(td(String.valueOf(it.getQty()), Element.ALIGN_LEFT));

                PdfPCell imeiCell = new PdfPCell(new Phrase(safe(it.getImeiText()),
                        new Font(Font.HELVETICA, 10)));
                imeiCell.setPadding(6);
                imeiCell.setNoWrap(false);
                imeiCell.setLeading(0, 1.2f);
                t.addCell(imeiCell);
            }
        }

        doc.add(t);
    }

    private void addSummary(Document doc, List<ImportReceiptLineDetail> lines) throws DocumentException {
        int totalLines = (lines == null) ? 0 : lines.size();
        int totalQty = 0;
        if (lines != null) for (ImportReceiptLineDetail it : lines) totalQty += it.getQty();

        Paragraph sumTitle = new Paragraph("Summary", B);
        sumTitle.setAlignment(Element.ALIGN_CENTER);
        sumTitle.setSpacingBefore(10);
        doc.add(sumTitle);

        Paragraph sum = new Paragraph("Total lines: " + totalLines + "\n" + "Total qty: " + totalQty, N);
        sum.setAlignment(Element.ALIGN_CENTER);
        sum.setSpacingAfter(10);
        doc.add(sum);

        doc.add(lineSeparator());
    }

    private void addSignatures(Document doc) throws DocumentException {
        Paragraph sigTitle = new Paragraph("Signatures", B);
        sigTitle.setSpacingBefore(6);
        sigTitle.setSpacingAfter(8);
        doc.add(sigTitle);

        PdfPTable sig = new PdfPTable(new float[]{33, 34, 33});
        sig.setWidthPercentage(100);

        sig.addCell(sigBox("Warehouse staff"));
        sig.addCell(sigBox("Supplier"));
        sig.addCell(sigBox("Manager"));

        doc.add(sig);
    }

    // ===== helpers =====
    private static PdfPCell th(String s) {
        PdfPCell c = new PdfPCell(new Phrase(s, B));
        c.setPadding(6);
        return c;
    }

    private static PdfPCell td(String s, int align) {
        PdfPCell c = new PdfPCell(new Phrase(s, N));
        c.setPadding(6);
        c.setHorizontalAlignment(align);
        c.setNoWrap(false);
        return c;
    }

    private static PdfPCell cellNoBorder(Phrase p) {
        PdfPCell c = new PdfPCell(p);
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(0);
        return c;
    }

    private static LineSeparator lineSeparator() {
        LineSeparator ls = new LineSeparator();
        ls.setLineWidth(1f);
        ls.setPercentage(100);
        return ls;
    }

    private static PdfPCell sigBox(String title) {
        PdfPCell c = new PdfPCell();
        c.setBorder(Rectangle.NO_BORDER);

        Paragraph p1 = new Paragraph(title, B);
        p1.setSpacingAfter(4);
        c.addElement(p1);

        c.addElement(new Paragraph("(Full name + sign)", N));
        c.addElement(new Paragraph("Date: ____/____/______", N));
        c.setPaddingRight(10);

        return c;
    }

    private static String safe(String s) {
        if (s == null) return "";
        return s.replaceAll("[\\r\\n\\t]+", " ")
                .replaceAll("\\s{2,}", " ")
                .trim();
    }

    private static String fmt(Timestamp ts) {
        if (ts == null) return "";
        return new java.text.SimpleDateFormat("dd/MM/yyyy hh:mm a").format(ts);
    }
}