/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package controller;

/**
 *
 * @author Admin
 */


import dal.DBContext;
import dal.ImportReceiptDAO;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;

import model.ImportReceiptDetail;
import model.ImportReceiptLineDetail;

import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.openpdf.text.*;
import org.openpdf.text.pdf.*;
import org.openpdf.text.pdf.draw.LineSeparator;

@WebServlet(name = "ImportReceiptPdf", urlPatterns = {"/import-receipt-pdf"})
public class ImportReceiptPdf extends HttpServlet {

    // ===== Company Info =====
    private static final String COMPANY_NAME    = "DTLA Mobile Warehouse Management";
    private static final String COMPANY_ADDRESS = "1 Meta Way (formerly 1 Hacker Way), Menlo Park, California 94025, USA";
    private static final String COMPANY_CONTACT = "Phone: 0965298768  |  Email: minhduchoang2410@gmail.com";

    private static final DateTimeFormatter UI_DTF  = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    private static final DateTimeFormatter RPT_DTF = DateTimeFormatter.ofPattern("yyMMddHHmmss");

    // ===== Footer =====
    private static class ReceiptFooter extends PdfPageEventHelper {
        private final Font f = new Font(Font.HELVETICA, 8, Font.NORMAL);
        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            try {
                PdfPTable footer = new PdfPTable(1);
                footer.setTotalWidth(document.right() - document.left());
                PdfPCell c = new PdfPCell(new Phrase(
                        "Generated by DTLA Mobile WMS - " + LocalDateTime.now().format(UI_DTF), f));
                c.setBorder(Rectangle.NO_BORDER);
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                footer.addCell(c);
                footer.writeSelectedRows(0, -1, document.left(), document.bottom() - 10, writer.getDirectContent());
            } catch (Exception ignored) {}
        }
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        String idRaw = req.getParameter("id");
        if (idRaw == null || idRaw.isBlank()) { resp.sendError(400, "Missing id"); return; }

        long importId;
        try { importId = Long.parseLong(idRaw.trim()); }
        catch (Exception e) { resp.sendError(400, "Invalid id"); return; }

        ImportReceiptDAO dao = new ImportReceiptDAO();
        ImportReceiptDetail header;
        List<ImportReceiptLineDetail> lines;

        try (var con = DBContext.getConnection()) {
            header = dao.getDetailHeader(con, importId);
            if (header == null) { resp.sendError(404, "Import receipt not found"); return; }
            lines = dao.getDetailLines(con, importId);
        } catch (Exception e) {
            throw new ServletException(e);
        }

        String fileName = "import-receipt-" + safe(header.getImportCode()) + ".pdf";
        String encoded  = URLEncoder.encode(fileName, StandardCharsets.UTF_8).replace("+", "%20");

        resp.setContentType("application/pdf");
        resp.setHeader("Content-Disposition", "attachment; filename*=UTF-8''" + encoded);

        Document doc = new Document(PageSize.A4, 36, 36, 36, 50);

        try {
            PdfWriter writer = PdfWriter.getInstance(doc, resp.getOutputStream());
            writer.setPageEvent(new ReceiptFooter());
            doc.open();
            writePdf(doc, header, lines);
        } catch (Exception e) {
            throw new ServletException(e);
        } finally {
            if (doc.isOpen()) doc.close();
        }
    }

    private void writePdf(Document doc, ImportReceiptDetail h, List<ImportReceiptLineDetail> lines)
            throws DocumentException {

        Font fH2 = new Font(Font.HELVETICA, 11, Font.BOLD);
        Font fH1 = new Font(Font.HELVETICA, 14, Font.BOLD);
        Font fN  = new Font(Font.HELVETICA, 9,  Font.NORMAL);
        Font fB  = new Font(Font.HELVETICA, 9,  Font.BOLD);

        // ===== TOP HEADER =====
        PdfPTable header = new PdfPTable(2);
        header.setWidthPercentage(100);
        header.setWidths(new float[]{3.2f, 1.2f});
        header.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        PdfPCell left = new PdfPCell();
        left.setBorder(Rectangle.NO_BORDER);
        left.addElement(new Paragraph(COMPANY_NAME, fH2));
        left.addElement(new Paragraph(COMPANY_ADDRESS, fN));
        left.addElement(new Paragraph(COMPANY_CONTACT, fN));

        String reportNo = "RPT-" + LocalDateTime.now().format(RPT_DTF);
        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);
        Paragraph pNo = new Paragraph("Report No: " + reportNo, fB);
        pNo.setAlignment(Element.ALIGN_RIGHT);
        Paragraph pDate = new Paragraph("Date: " + LocalDate.now(), fB);
        pDate.setAlignment(Element.ALIGN_RIGHT);
        right.addElement(pNo);
        right.addElement(pDate);

        header.addCell(left);
        header.addCell(right);
        doc.add(header);

        doc.add(blank(6));

        // ===== CENTER TITLE =====
        Paragraph title = new Paragraph("IMPORT RECEIPT", fH1);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);

        Paragraph sub = new Paragraph("Receipt No: " + safe(h.getImportCode()), fB);
        sub.setAlignment(Element.ALIGN_CENTER);
        sub.setSpacingAfter(6f);
        doc.add(sub);

        doc.add(dashLine());

        // ===== INFO BLOCK 2 columns =====
        PdfPTable info = new PdfPTable(2);
        info.setWidthPercentage(100);
        info.setWidths(new float[]{1f, 1f});
        info.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        PdfPCell infoL = new PdfPCell(new Phrase(
                "Receipt Date: " + safe(fmt(h.getReceiptDate())) + "\n"
              + "Supplier: " + safe(h.getSupplierName()) + "\n"
              + "Status: " + safe(h.getStatus()),
                fN));
        infoL.setBorder(Rectangle.NO_BORDER);

        PdfPCell infoR = new PdfPCell(new Phrase(
                "Created by: " + safe(h.getCreatedByName()) + "\n"
              + "Generated at: " + LocalDateTime.now().format(UI_DTF) + "\n"
              + "Note: " + safe(h.getNote()),
                fN));
        infoR.setBorder(Rectangle.NO_BORDER);

        info.addCell(infoL);
        info.addCell(infoR);
        doc.add(info);

        doc.add(blank(6));
        doc.add(dashLine());

        // ===== ITEMS =====
        Paragraph itemsLabel = new Paragraph("ITEMS", fB);
        itemsLabel.setSpacingBefore(6f);
        itemsLabel.setSpacingAfter(6f);
        doc.add(itemsLabel);

        PdfPTable t = new PdfPTable(6);
        t.setWidthPercentage(100);
        t.setHeaderRows(1);
        t.setWidths(new float[]{0.6f, 1.6f, 2.0f, 0.7f, 0.7f, 2.4f});

        addTH(t, "#", fB);
        addTH(t, "Product", fB);
        addTH(t, "SKU", fB);
        addTH(t, "In Stock", fB);
        addTH(t, "Qty", fB);
        addTH(t, "IMEI List", fB);

        if (lines == null || lines.isEmpty()) {
            PdfPCell empty = new PdfPCell(new Phrase("No data", fN));
            empty.setColspan(6);
            empty.setHorizontalAlignment(Element.ALIGN_CENTER);
            empty.setPadding(8f);
            empty.setBorder(Rectangle.NO_BORDER);
            t.addCell(empty);
        } else {
            int idx = 1;
            for (ImportReceiptLineDetail it : lines) {
                addTD(t, String.valueOf(idx++), fN, Element.ALIGN_CENTER);
                addTD(t, safe(it.getProductCode()), fN, Element.ALIGN_LEFT);
                addTD(t, safe(it.getSkuCode()), fN, Element.ALIGN_LEFT);
                addTD(t, String.valueOf(it.getInStock()), fN, Element.ALIGN_CENTER);
                addTD(t, String.valueOf(it.getQty()), fN, Element.ALIGN_CENTER);

                PdfPCell imeiCell = new PdfPCell(new Phrase(safe(it.getImeiText()),
                        new Font(Font.HELVETICA, 8)));
                imeiCell.setBorder(Rectangle.NO_BORDER);
                imeiCell.setPadding(5f);
                imeiCell.setNoWrap(false);
                imeiCell.setLeading(0, 1.3f);
                t.addCell(imeiCell);
            }
        }
        doc.add(t);

        // ===== SUMMARY (right side) =====
        doc.add(blank(8));

        int totalLines = (lines == null) ? 0 : lines.size();
        int totalQty   = 0;
        if (lines != null) for (ImportReceiptLineDetail it : lines) totalQty += it.getQty();

        PdfPTable sumWrap = new PdfPTable(2);
        sumWrap.setWidthPercentage(100);
        sumWrap.setWidths(new float[]{2.2f, 1.0f});
        sumWrap.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        PdfPCell blankLeft = new PdfPCell(new Phrase("", fN));
        blankLeft.setBorder(Rectangle.NO_BORDER);

        PdfPTable sum = new PdfPTable(1);
        PdfPCell sTitle = new PdfPCell(new Phrase("Summary", fB));
        sTitle.setBorder(Rectangle.NO_BORDER);
        sTitle.setPaddingBottom(4f);
        sum.addCell(sTitle);
        sum.addCell(noBorderLine("Total lines: " + totalLines, fN));
        sum.addCell(noBorderLine("Total qty  : " + totalQty, fN));

        PdfPCell sumRight = new PdfPCell(sum);
        sumRight.setBorder(Rectangle.NO_BORDER);

        sumWrap.addCell(blankLeft);
        sumWrap.addCell(sumRight);
        doc.add(sumWrap);

        doc.add(blank(10));
        doc.add(dashLine());

        // ===== SIGNATURES =====
        Paragraph sigTitle = new Paragraph("Signatures", fB);
        sigTitle.setSpacingBefore(8f);
        sigTitle.setSpacingAfter(8f);
        doc.add(sigTitle);

        PdfPTable sig = new PdfPTable(new float[]{33, 34, 33});
        sig.setWidthPercentage(100);
        sig.addCell(sigBox("Warehouse Staff", fB, fN));
        sig.addCell(sigBox("Supplier", fB, fN));
        sig.addCell(sigBox("Manager", fB, fN));
        doc.add(sig);
    }

    // ===== Helpers =====
    private static Element dashLine() {
        LineSeparator ls = new LineSeparator();
        ls.setLineWidth(1f);
        ls.setPercentage(100);
        ls.setLineColor(new java.awt.Color(50, 50, 50));
        return ls;
    }

    private static Paragraph blank(float space) {
        Paragraph p = new Paragraph(" ");
        p.setSpacingAfter(space);
        return p;
    }

    private static void addTH(PdfPTable t, String text, Font f) {
        PdfPCell c = new PdfPCell(new Phrase(text, f));
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(5f);
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        t.addCell(c);
    }

    private static void addTD(PdfPTable t, String text, Font f, int align) {
        PdfPCell c = new PdfPCell(new Phrase(text == null ? "" : text, f));
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(5f);
        c.setHorizontalAlignment(align);
        t.addCell(c);
    }

    private static PdfPCell noBorderLine(String text, Font f) {
        PdfPCell c = new PdfPCell(new Phrase(text, f));
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(2f);
        return c;
    }

    private static PdfPCell sigBox(String title, Font fB, Font fN) {
        PdfPCell c = new PdfPCell();
        c.setBorder(Rectangle.NO_BORDER);
        Paragraph p1 = new Paragraph(title, fB);
        p1.setSpacingAfter(4);
        c.addElement(p1);
        c.addElement(new Paragraph("(Full name + sign)", fN));
        c.addElement(new Paragraph("Date: ____/____/______", fN));
        c.setPaddingRight(10);
        return c;
    }

    private static String safe(String s) {
        return (s == null) ? "" : s;
    }

    private static String fmt(Timestamp ts) {
        if (ts == null) return "";
        return new java.text.SimpleDateFormat("dd/MM/yyyy hh:mm a").format(ts);
    }
}