/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
/**
 *
 * @author Admin
 */
package util;

import java.io.OutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import org.openpdf.text.Document;
import org.openpdf.text.DocumentException;
import org.openpdf.text.Element;
import org.openpdf.text.Font;
import org.openpdf.text.Paragraph;
import org.openpdf.text.Phrase;
import org.openpdf.text.Rectangle;
import org.openpdf.text.pdf.PdfPCell;
import org.openpdf.text.pdf.PdfPTable;
import org.openpdf.text.pdf.PdfPageEventHelper;
import org.openpdf.text.pdf.PdfWriter;
import org.openpdf.text.pdf.draw.LineSeparator;

public class PdfExportUtil {

    private static final String COMPANY_NAME = "DTLA Mobile Warehouse Management";
    private static final String COMPANY_ADDRESS = "1 Meta Way (formerly 1 Hacker Way), Menlo Park, California 94025, USA";
    private static final String COMPANY_CONTACT = "Phone: 0965298768  |  Email: minhduchoang2410@gmail.com";

    private static final DateTimeFormatter UI_DTF = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    private static final DateTimeFormatter RPT_DTF = DateTimeFormatter.ofPattern("yyMMddHHmmss");

    private static class ReportFooter extends PdfPageEventHelper {

        private final Font f = new Font(Font.HELVETICA, 8, Font.NORMAL);

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            try {
                PdfPTable footer = new PdfPTable(1);
                footer.setTotalWidth(document.right() - document.left());

                PdfPCell c = new PdfPCell(new Phrase(
                        "Generated by DTLA Mobile WMS - " + LocalDateTime.now().format(UI_DTF)
                        + " | Page " + writer.getPageNumber(),
                        f
                ));
                c.setBorder(Rectangle.NO_BORDER);
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                footer.addCell(c);

                footer.writeSelectedRows(
                        0, -1,
                        document.left(),
                        document.bottom() - 10,
                        writer.getDirectContent()
                );
            } catch (Exception ignored) {
            }
        }
    }

    public static void export(
            OutputStream os,
            String title,
            Map<String, String> filters,
            Map<String, String> summary,
            List<String> headers,
            List<List<String>> rows,
            Rectangle pageSize
    ) throws Exception {

        Document doc = new Document(pageSize, 36, 36, 36, 50);
        PdfWriter writer = PdfWriter.getInstance(doc, os);
        writer.setPageEvent(new ReportFooter());
        doc.open();

        writePdf(doc, title, filters, summary, headers, rows);

        if (doc.isOpen()) {
            doc.close();
        }
    }

    private static void writePdf(
            Document doc,
            String reportTitle,
            Map<String, String> filters,
            Map<String, String> summary,
            List<String> headers,
            List<List<String>> rows
    ) throws DocumentException {

        Font fH2 = new Font(Font.HELVETICA, 11, Font.BOLD);
        Font fH1 = new Font(Font.HELVETICA, 14, Font.BOLD);
        Font fN = new Font(Font.HELVETICA, 9, Font.NORMAL);
        Font fB = new Font(Font.HELVETICA, 9, Font.BOLD);

        // ===== TOP HEADER =====
        PdfPTable header = new PdfPTable(2);
        header.setWidthPercentage(100);
        header.setWidths(new float[]{3.2f, 1.2f});
        header.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        PdfPCell left = new PdfPCell();
        left.setBorder(Rectangle.NO_BORDER);
        left.addElement(new Paragraph(COMPANY_NAME, fH2));
        left.addElement(new Paragraph(COMPANY_ADDRESS, fN));
        left.addElement(new Paragraph(COMPANY_CONTACT, fN));

        String reportNo = "RPT-" + LocalDateTime.now().format(RPT_DTF);
        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);

        Paragraph pNo = new Paragraph("Report No: " + reportNo, fB);
        pNo.setAlignment(Element.ALIGN_RIGHT);
        Paragraph pDate = new Paragraph("Date: " + LocalDate.now(), fB);
        pDate.setAlignment(Element.ALIGN_RIGHT);

        right.addElement(pNo);
        right.addElement(pDate);

        header.addCell(left);
        header.addCell(right);
        doc.add(header);

        doc.add(blank(6));

        // ===== CENTER TITLE =====
        Paragraph title = new Paragraph(reportTitle.toUpperCase(), fH1);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);

        Paragraph sub = new Paragraph("Generated at: " + LocalDateTime.now().format(UI_DTF), fB);
        sub.setAlignment(Element.ALIGN_CENTER);
        sub.setSpacingAfter(6f);
        doc.add(sub);

        doc.add(dashLine());

        // ===== FILTER + SUMMARY BLOCK =====
        PdfPTable info = new PdfPTable(2);
        info.setWidthPercentage(100);
        info.setWidths(new float[]{1f, 1f});
        info.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        PdfPCell infoL = new PdfPCell();
        infoL.setBorder(Rectangle.NO_BORDER);
        infoL.addElement(new Paragraph("Applied Filters", fB));
        for (Map.Entry<String, String> e : filters.entrySet()) {
            infoL.addElement(new Paragraph(e.getKey() + ": " + safe(e.getValue()), fN));
        }

        PdfPCell infoR = new PdfPCell();
        infoR.setBorder(Rectangle.NO_BORDER);
        infoR.addElement(new Paragraph("Summary", fB));
        for (Map.Entry<String, String> e : summary.entrySet()) {
            infoR.addElement(new Paragraph(e.getKey() + ": " + safe(e.getValue()), fN));
        }

        info.addCell(infoL);
        info.addCell(infoR);
        doc.add(info);

        doc.add(blank(6));
        doc.add(dashLine());

        // ===== DATA TABLE =====
        Paragraph itemsLabel = new Paragraph("DATA", fB);
        itemsLabel.setSpacingBefore(6f);
        itemsLabel.setSpacingAfter(6f);
        doc.add(itemsLabel);

        PdfPTable t = new PdfPTable(headers.size());
        t.setWidthPercentage(100);
        t.setHeaderRows(1);

        float[] widths = buildColumnWidths(headers.size());
        t.setWidths(widths);

        for (String h : headers) {
            addTH(t, h, fB);
        }

        if (rows == null || rows.isEmpty()) {
            PdfPCell empty = new PdfPCell(new Phrase("No data", fN));
            empty.setColspan(headers.size());
            empty.setHorizontalAlignment(Element.ALIGN_CENTER);
            empty.setPadding(8f);
            empty.setBorder(Rectangle.NO_BORDER);
            t.addCell(empty);
        } else {
            for (List<String> row : rows) {
                for (String cell : row) {
                    addTD(t, safe(cell), fN, Element.ALIGN_LEFT);
                }
            }
        }

        doc.add(t);

        // ===== SUMMARY RIGHT =====
        doc.add(blank(8));

        PdfPTable sumWrap = new PdfPTable(2);
        sumWrap.setWidthPercentage(100);
        sumWrap.setWidths(new float[]{2.2f, 1.0f});
        sumWrap.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        PdfPCell blankLeft = new PdfPCell(new Phrase("", fN));
        blankLeft.setBorder(Rectangle.NO_BORDER);

        PdfPTable sum = new PdfPTable(1);
        PdfPCell sTitle = new PdfPCell(new Phrase("Quick Summary", fB));
        sTitle.setBorder(Rectangle.NO_BORDER);
        sTitle.setPaddingBottom(4f);
        sum.addCell(sTitle);
        sum.addCell(noBorderLine("Columns   : " + headers.size(), fN));
        sum.addCell(noBorderLine("Row count : " + (rows == null ? 0 : rows.size()), fN));

        PdfPCell sumRight = new PdfPCell(sum);
        sumRight.setBorder(Rectangle.NO_BORDER);

        sumWrap.addCell(blankLeft);
        sumWrap.addCell(sumRight);
        doc.add(sumWrap);

        doc.add(blank(10));
        doc.add(dashLine());

        // ===== SIGNATURES =====
        Paragraph sigTitle = new Paragraph("Signatures", fB);
        sigTitle.setSpacingBefore(8f);
        sigTitle.setSpacingAfter(8f);
        doc.add(sigTitle);

        PdfPTable sig = new PdfPTable(new float[]{33, 34, 33});
        sig.setWidthPercentage(100);
        sig.addCell(sigBox("Prepared by", fB, fN));
        sig.addCell(sigBox("Reviewed by", fB, fN));
        sig.addCell(sigBox("Approved by", fB, fN));
        doc.add(sig);
    }

    private static float[] buildColumnWidths(int size) {
        float[] widths = new float[size];
        for (int i = 0; i < size; i++) {
            widths[i] = 1f;
        }
        return widths;
    }

    private static Element dashLine() {
        LineSeparator ls = new LineSeparator();
        ls.setLineWidth(1f);
        ls.setPercentage(100);
        ls.setLineColor(new java.awt.Color(50, 50, 50));
        return ls;
    }

    private static Paragraph blank(float space) {
        Paragraph p = new Paragraph(" ");
        p.setSpacingAfter(space);
        return p;
    }

    private static void addTH(PdfPTable t, String text, Font f) {
        PdfPCell c = new PdfPCell(new Phrase(text, f));
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(5f);
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        t.addCell(c);
    }

    private static void addTD(PdfPTable t, String text, Font f, int align) {
        PdfPCell c = new PdfPCell(new Phrase(text == null ? "" : text, f));
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(5f);
        c.setHorizontalAlignment(align);
        c.setNoWrap(false);
        t.addCell(c);
    }

    private static PdfPCell noBorderLine(String text, Font f) {
        PdfPCell c = new PdfPCell(new Phrase(text, f));
        c.setBorder(Rectangle.NO_BORDER);
        c.setPadding(2f);
        return c;
    }

    private static PdfPCell sigBox(String title, Font fB, Font fN) {
        PdfPCell c = new PdfPCell();
        c.setBorder(Rectangle.NO_BORDER);

        Paragraph p1 = new Paragraph(title, fB);
        p1.setSpacingAfter(4);
        c.addElement(p1);
        c.addElement(new Paragraph("(Full name + sign)", fN));
        c.addElement(new Paragraph("Date: ____/____/______", fN));
        c.setPaddingRight(10);

        return c;
    }

    private static String safe(String s) {
        return s == null ? "" : s;
    }
}
